name: stepper_complete
description: "StepperComplete: A customizable Flutter package for creating intuitive and responsive step-by-step wizards."
version: 0.1.1
homepage: https://github.com/Felipe-Linhares
repository: https://github.com/Felipe-Linhares/stepper_complete

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stepper_complete
      ios:
        default_package: stepper_complete
      # linux:
      #   default_package: audioplayers_linux
      # macos:
      #   default_package: audioplayers_darwin
      # web:
      #   default_package: audioplayers_web
      # windows:
      #   default_package: audioplayers_windows


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

