name: Publish to pub.dev

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.0'
      - name: Install dependencies
        run: flutter pub get
      - uses: dart-lang/setup-dart@v1
      - name: Publish to pub.dev
        run: dart pub publish --force
        env:
          PUB_CREDENTIALS: ${{ secrets.CREDENTIAL_JSON }}